; Counting records in a global array via FOR/$ORDER.
SET ^PATIENT(1)="DOE,JANE^34^F"
SET ^PATIENT(2)="SMITH,JOHN^58^M"
SET ^PATIENT(3)="LEE,KIM^27^F"
SET COUNT=0
SET IDX=""
FOR  SET IDX=$ORDER(^PATIENT(IDX)) QUIT:IDX=""  SET COUNT=COUNT+1
WRITE "TOTAL PATIENTS: ",COUNT,!
